"""Add tables courses and images

Revision ID: 907c315e5f94
Revises: 84aa5594f1b6
Create Date: 2022-05-25 17:17:49.244645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '907c315e5f94'
down_revision = '84aa5594f1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('md5_hash', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('md5_hash', name=op.f('uq_images_md5_hash'))
    )
    op.add_column('courses', sa.Column('rating_sum', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('rating_num', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('background_image_id', sa.String(length=100), nullable=True))
    op.add_column('courses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(op.f('fk_courses_category_id_categories'), 'courses', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('fk_courses_background_image_id_images'), 'courses', 'images', ['background_image_id'], ['id'])
    op.create_foreign_key(op.f('fk_courses_author_id_users_lab6'), 'courses', 'users_lab6', ['author_id'], ['id'])
    op.drop_column('courses', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_courses_author_id_users_lab6'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_background_image_id_images'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('fk_courses_category_id_categories'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'background_image_id')
    op.drop_column('courses', 'author_id')
    op.drop_column('courses', 'category_id')
    op.drop_column('courses', 'rating_num')
    op.drop_column('courses', 'rating_sum')
    op.drop_table('images')
    # ### end Alembic commands ###
