"""Add User

Revision ID: eea5aebe9930
Revises: b007a611945e
Create Date: 2022-05-18 18:23:16.236770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea5aebe9930'
down_revision = 'b007a611945e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_lab6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_lab6')),
    sa.UniqueConstraint('login', name=op.f('uq_users_lab6_login')),
    sa.UniqueConstraint('password_hash', name=op.f('uq_users_lab6_password_hash'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_lab6')
    # ### end Alembic commands ###
